name: The Aroma
favicon: null
layout_spectrum: 0.5653481015469879
typography_spectrum: 0.6890195491723716
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4486951718572527
  lightness: 0.007492138538509607
  saturation: 0.027626274153590202
  rhythmicContrast: 0.6732731705997139
purpose: []
