typography_spectrum: 0.6890195491723716
color:
  brandColors:
    - '#65270C'
    - '#F3CE5C'
    - '#B46502'
    - '#6F99C5'
    - '#FCFCFB'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.6875
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2741936
analytics:
  google: null
  facebook: null
  twitter: null
name: The Aroma
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Our Website
    url: thearoma.tw
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Good Coffee, Great Friends'
purpose: []
